# Generated by Django 5.1.2 on 2025-01-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB_client', '0003_remove_resume_contact_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='level',
            field=models.CharField(choices=[('Среднее', 'Среднее'), ('Среднее специальное', 'Среднее специальное'), ('Неоконченное высшее', 'Неоконченное высшее'), ('Высшее', 'Высшее'), ('Бакалавр', 'Бакалвар'), ('Магистр', 'Магистр'), ('Кандидат наук', 'Кандидат наук'), ('Доктор наук', 'Доктор наук')], default='Male', max_length=25),
        ),
    ]
