# Generated by Django 5.1.2 on 2025-01-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB_client', '0004_education_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='degree',
            new_name='place',
        ),
        migrations.RemoveField(
            model_name='education',
            name='institution',
        ),
        migrations.AlterField(
            model_name='education',
            name='level',
            field=models.CharField(choices=[('Среднее', 'Среднее'), ('Среднее специальное', 'Среднее специальное'), ('Неоконченное высшее', 'Неоконченное высшее'), ('Высшее', 'Высшее'), ('Бакалавр', 'Бакалвар'), ('Магистр', 'Магистр'), ('Кандидат наук', 'Кандидат наук'), ('Доктор наук', 'Доктор наук')], default='Среднее', max_length=25),
        ),
    ]
