# Generated by Django 5.1.2 on 2025-01-03 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB_client', '0005_rename_degree_education_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='level',
            field=models.CharField(choices=[('secondary', 'Среднее'), ('secondary-specialised', 'Среднее специальное'), ('uncompleted-higher', 'Неоконченное высшее'), ('higher', 'Высшее'), ('bachelor', 'Бакалвар'), ('master', 'Магистр'), ('Ph', 'Кандидат наук'), ('PhD', 'Доктор наук')], default='Среднее', max_length=25),
        ),
        migrations.AlterField(
            model_name='education',
            name='year',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinValueValidator(1940), django.core.validators.MaxValueValidator(2025)], verbose_name='Год'),
        ),
    ]
