# Generated by Django 5.1.2 on 2025-01-04 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DB_client', '0007_alter_workexperience_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='employer_id',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
