# Generated by Django 5.1.2 on 2025-01-04 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB_client', '0008_remove_job_employer_id_delete_application_delete_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('requirements', models.JSONField()),
                ('conditions', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('Full_Time', 'Полная занятость'), ('Part_Time', 'Частичная занятость'), ('Remote', 'Удалённая работа')], max_length=10)),
                ('experience_level', models.CharField(choices=[('no_expirience', 'Без опыта'), ('1_between_3', 'От 1 года до 3 лет'), ('3_between_6', 'От 3 до 6 лет'), ('more_than_6', 'От 3 до 6 лет')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'В ожидании'), ('Rejected', 'Отклонено'), ('Accepted', 'Принято')], default='Pending', max_length=10)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB_client.resume')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB_client.job')),
            ],
        ),
    ]
