# Generated by Django 5.1.2 on 2025-01-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB_client', '0009_job_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_salary', models.DecimalField(decimal_places=0, max_digits=8, null=True)),
                ('personal_qualities', models.TextField()),
                ('experience_level', models.CharField(choices=[('no_expirience', 'Без опыта'), ('1_between_3', 'От 1 года до 3 лет'), ('3_between_6', 'От 3 до 6 лет'), ('more_than_6', 'От 3 до 6 лет')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='salary_from',
            field=models.DecimalField(decimal_places=0, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_to',
            field=models.DecimalField(decimal_places=0, max_digits=8, null=True),
        ),
    ]
