# Generated by Django 5.1.2 on 2025-01-11 09:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB_client', '0010_additionalinfo_job_salary_from_job_salary_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatars'),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_network',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Мужской'), ('Female', 'Женский'), ('Other', 'Другое')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Введите правильный номер телефона в формате: '+999999999'. До 15 цифр.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
