# Generated by Django 5.1.2 on 2025-01-15 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DB_client', '0012_additionalinfo_profession_profile_emp_post_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdditionalInfo',
        ),
    ]
