# Generated by Django 5.1.2 on 2025-01-15 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB_client', '0013_delete_additionalinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(default='Не указано', max_length=50)),
                ('desired_salary', models.DecimalField(decimal_places=0, max_digits=8, null=True)),
                ('personal_qualities', models.TextField()),
                ('experience_level', models.CharField(choices=[('no_expirience', 'Без опыта'), ('1_between_3', 'От 1 года до 3 лет'), ('3_between_6', 'От 3 до 6 лет'), ('more_than_6', 'От 3 до 6 лет')], max_length=20)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB_client.resume')),
            ],
        ),
    ]
