# Generated by Django 5.1.2 on 2025-01-15 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DB_client', '0014_additionalinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
