# Generated by Django 5.1.2 on 2025-01-15 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB_client', '0015_delete_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB_client.job')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB_client.resume')),
            ],
        ),
    ]
